### ISSUE TITLE
Change the marker model and controller

### ISSUE THREAD

**Issue by wagoid** [ArthurVilaca/AZCMap#5]
Add the important properties to the marker model:

location (useful reference: http://tugdualgrall.blogspot.com.br/2014/08/introduction-to-mongodb-geospatial.html)
pictureUrl (if provided)
dateAdded
creatorIp
type: stagnant water or mosquito
--Anything else needed

**Comment by ArthurVilaca** [comment]
I think we can also get the approximate location of the creator at creation of the marker

**Comment by wagoid** [comment]
Merged issue_5 into master.
